"""add win_event column

Revision ID: 0991a7155f74
Revises: 3d9bbf1bbbb0
Create Date: 2025-04-17 17:24:35.316290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0991a7155f74"
down_revision: Union[str, None] = "3d9bbf1bbbb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("win_event", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "match", "event", ["win_event"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_column("match", "win_event")
    # ### end Alembic commands ###
