"""add win_event column

Revision ID: 26e82beb819a
Revises: 0991a7155f74
Create Date: 2025-04-17 17:25:47.309961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26e82beb819a"
down_revision: Union[str, None] = "0991a7155f74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("win_event_id", sa.Integer(), nullable=True))
    op.drop_constraint("match_win_event_fkey", "match", type_="foreignkey")
    op.create_foreign_key(None, "match", "event", ["win_event_id"], ["id"], ondelete="CASCADE")
    op.drop_column("match", "win_event")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match", sa.Column("win_event", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "match", type_="foreignkey")
    op.create_foreign_key(
        "match_win_event_fkey", "match", "event", ["win_event"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("match", "win_event_id")
    # ### end Alembic commands ###
