"""delete outcome fields and create event_outcome

Revision ID: 26f802bbc5c6
Revises: 0c17698f52bc
Create Date: 2025-06-03 16:21:19.863117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26f802bbc5c6"
down_revision: Union[str, None] = "0c17698f52bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_outcome",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("outcome_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["outcome_id"], ["outcome.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "outcome_id"),
    )
    op.drop_constraint("event_first_outcome_id_fkey", "event", type_="foreignkey")
    op.drop_constraint("event_second_outcome_id_fkey", "event", type_="foreignkey")
    op.drop_column("event", "second_outcome_id")
    op.drop_column("event", "first_outcome_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event", sa.Column("first_outcome_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "event", sa.Column("second_outcome_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "event_second_outcome_id_fkey", "event", "outcome", ["second_outcome_id"], ["id"]
    )
    op.create_foreign_key(
        "event_first_outcome_id_fkey", "event", "outcome", ["first_outcome_id"], ["id"]
    )
    op.drop_table("event_outcome")
    # ### end Alembic commands ###
