"""add icon_path field in game model

Revision ID: 3d9bbf1bbbb0
Revises: 7bb9758fd714
Create Date: 2025-04-16 17:32:52.230664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d9bbf1bbbb0"
down_revision: Union[str, None] = "7bb9758fd714"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("icon_path", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "icon_path")
    # ### end Alembic commands ###
