"""add game_id field

Revision ID: 546db49ea6f4
Revises: d310f946ca40
Create Date: 2025-06-07 20:50:50.157205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "546db49ea6f4"
down_revision: Union[str, None] = "d310f946ca40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_type", sa.Column("game_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "event_type", "game", ["game_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event_type", type_="foreignkey")
    op.drop_column("event_type", "game_id")
    # ### end Alembic commands ###
