"""add icon_path field in ea_team

Revision ID: 7bb9758fd714
Revises: 2909544decc0
Create Date: 2025-04-16 14:15:30.539276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bb9758fd714"
down_revision: Union[str, None] = "2909544decc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ea_team", sa.Column("icon_path", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ea_team", "icon_path")
    # ### end Alembic commands ###
