"""make a one2one

Revision ID: 8b3824544d04
Revises: 26e82beb819a
Create Date: 2025-04-17 17:43:26.612551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b3824544d04"
down_revision: Union[str, None] = "26e82beb819a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "match", ["win_event_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match", type_="unique")
    # ### end Alembic commands ###
