"""create outcome type model and nullable outcome name

Revision ID: d310f946ca40
Revises: 26f802bbc5c6
Create Date: 2025-06-07 20:42:15.973491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d310f946ca40"
down_revision: Union[str, None] = "26f802bbc5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_type",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.add_column("event", sa.Column("type_code", sa.String(length=32), nullable=False))
    op.create_foreign_key(None, "event", "event_type", ["type_code"], ["code"], ondelete="CASCADE")
    op.alter_column("outcome", "name", existing_type=sa.VARCHAR(length=32), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("outcome", "name", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_column("event", "type_code")
    op.drop_table("event_type")
    # ### end Alembic commands ###
